"""Turn any URL into a video brief.

The user pastes a news article, blog post, paper or video link and the pipeline builds
a video from it. Extraction is layered so a single failing method never blocks the run:

1. trafilatura - the main readability extractor, works on most news and blog pages
2. YouTube metadata - oEmbed plus public Piped mirrors, since video pages carry no article text
3. A built-in HTML fallback - strips tags when trafilatura finds nothing

Everything is free and keyless. Nothing is generated by an AI video model; the article
only supplies the topic and facts, and the visuals still come from real stock footage.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from html import unescape
from typing import Any, Dict, List, Optional
from urllib.parse import parse_qs, urlparse

import requests

from utility.core.user_agents import agents_for, headers_for, remember_success

LOGGER = logging.getLogger("article_extractor")
if not LOGGER.handlers:
    _h = logging.StreamHandler()
    _h.setFormatter(logging.Formatter("[%(name)s] %(message)s"))
    LOGGER.addHandler(_h)
LOGGER.setLevel(logging.INFO)

FETCH_TIMEOUT = 25
MIN_USEFUL_WORDS = 40
# Below this a page cannot carry a script by itself and enrichment is attempted.
THIN_PAGE_WORDS = 250

YOUTUBE_HOSTS = ("youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com")
PIPED_MIRRORS = (
    "https://api.piped.private.coffee",
    "https://pipedapi.adminforge.de",
    "https://pipedapi.drgns.space",
)


class ExtractionError(Exception):
    """Raised when no usable text could be recovered from a URL."""


@dataclass
class Article:
    """A cleaned article ready to be turned into a video brief."""

    url: str
    title: str
    text: str
    author: str = ""
    published: str = ""
    site: str = ""
    description: str = ""
    source_type: str = "article"
    images: List[str] = field(default_factory=list)

    # Set when a thin page was topped up from the pages it links to.
    supporting_text: str = ""
    supporting_sources: List[Dict[str, Any]] = field(default_factory=list)

    @property
    def word_count(self) -> int:
        """Number of words in the extracted body text."""
        return len(self.text.split())

    @property
    def total_word_count(self) -> int:
        """Words available to the script, including supporting material."""
        return self.word_count + len(self.supporting_text.split())

    @property
    def was_enriched(self) -> bool:
        """True when supporting material was pulled from linked pages."""
        return bool(self.supporting_sources)

    @property
    def full_text(self) -> str:
        """Main text plus any supporting material, clearly separated."""
        if not self.supporting_text:
            return self.text
        return f"{self.text}\n\n{self.supporting_text}"

    def as_dict(self) -> Dict[str, Any]:
        """Serializable summary for the UI."""
        return {
            "url": self.url,
            "title": self.title,
            "author": self.author,
            "published": self.published,
            "site": self.site,
            "source_type": self.source_type,
            "word_count": self.word_count,
            "total_word_count": self.total_word_count,
            "supporting_sources": self.supporting_sources,
            "preview": self.text[:400],
        }


# ----------------------------------------------------------------------
# Fetching
# ----------------------------------------------------------------------
def normalize_url(url: str) -> str:
    """Add a scheme when the user pastes a bare domain."""
    url = (url or "").strip()
    if not url:
        return ""
    if not re.match(r"^https?://", url, re.IGNORECASE):
        url = "https://" + url
    return url


def is_valid_url(url: str) -> bool:
    """Basic structural check before any network call."""
    try:
        parsed = urlparse(normalize_url(url))
        return bool(parsed.scheme in ("http", "https") and parsed.netloc and "." in parsed.netloc)
    except ValueError:
        return False


def fetch_html(url: str) -> Optional[str]:
    """Download a page, rotating User-Agents when a host refuses one."""
    from utility.core.user_agents import RETRYABLE_BLOCK_CODES

    session = requests.Session()
    connection_failures = 0
    try:
        for index, agent in enumerate(agents_for(url)):
            try:
                response = session.get(
                    url, headers=headers_for(agent), timeout=FETCH_TIMEOUT, allow_redirects=True
                )
            except (requests.ConnectionError, requests.Timeout) as exc:
                connection_failures += 1
                # A dead host or DNS failure will never be fixed by a different agent.
                if connection_failures >= 2:
                    LOGGER.info("%s is unreachable.", urlparse(url).netloc)
                    return None
                LOGGER.info("Request to %s failed: %s", url[:60], str(exc)[:60])
                continue
            except requests.RequestException as exc:
                LOGGER.info("Request to %s failed: %s", url[:60], str(exc)[:70])
                continue
            if response.ok:
                if index:
                    LOGGER.info("Page accepted User-Agent #%d.", index + 1)
                remember_success(url, agent)
                response.encoding = response.encoding or "utf-8"
                return response.text
            if response.status_code not in RETRYABLE_BLOCK_CODES:
                LOGGER.info("Page returned HTTP %s.", response.status_code)
                return None
        return None
    finally:
        session.close()


# ----------------------------------------------------------------------
# YouTube
# ----------------------------------------------------------------------
def youtube_id(url: str) -> Optional[str]:
    """Extract the video id from any YouTube URL form."""
    parsed = urlparse(url)
    host = parsed.netloc.lower().replace("www.", "")
    if host == "youtu.be":
        return parsed.path.lstrip("/").split("/")[0] or None
    if "youtube" in host:
        if parsed.path == "/watch":
            return (parse_qs(parsed.query).get("v") or [None])[0]
        match = re.match(r"^/(?:embed|shorts|v)/([\w-]+)", parsed.path)
        if match:
            return match.group(1)
    return None


def extract_youtube(url: str) -> Optional[Article]:
    """Build an Article from a YouTube link using keyless public endpoints."""
    video_id = youtube_id(url)
    if not video_id:
        return None

    title = ""
    author = ""
    description = ""

    try:
        response = requests.get(
            "https://www.youtube.com/oembed",
            params={"url": f"https://www.youtube.com/watch?v={video_id}", "format": "json"},
            timeout=FETCH_TIMEOUT,
        )
        if response.ok:
            payload = response.json()
            title = payload.get("title", "")
            author = payload.get("author_name", "")
    except (requests.RequestException, ValueError) as exc:
        LOGGER.info("YouTube oEmbed failed: %s", str(exc)[:70])

    for mirror in PIPED_MIRRORS:
        try:
            response = requests.get(f"{mirror}/streams/{video_id}", timeout=FETCH_TIMEOUT)
            if not response.ok:
                continue
            payload = response.json()
            title = title or payload.get("title", "")
            author = author or payload.get("uploader", "")
            description = payload.get("description", "") or ""
            if description:
                break
        except (requests.RequestException, ValueError):
            continue

    description = re.sub(r"<[^>]+>", " ", description)
    description = unescape(re.sub(r"\s+", " ", description)).strip()

    if not title:
        return None

    body = description if len(description.split()) >= MIN_USEFUL_WORDS else title
    return Article(
        url=url,
        title=title,
        text=body,
        author=author,
        site="YouTube",
        description=description[:500],
        source_type="youtube",
    )


# ----------------------------------------------------------------------
# HTML fallback
# ----------------------------------------------------------------------
def _clean_author(author: str) -> str:
    """Reject boilerplate that wikis and CMS templates expose as an author name."""
    author = re.sub(r"\s+", " ", author or "").strip()
    if not author or len(author) > 60 or len(author.split()) > 6:
        return ""
    junk = ("authority control", "database", "wikipedia", "editor", "staff", "admin",
            "contributor", "http")
    if any(word in author.lower() for word in junk):
        return ""
    return author


def strip_html(html: str) -> str:
    """Very small readability fallback used when trafilatura returns nothing."""
    html = re.sub(r"(?is)<(script|style|nav|header|footer|aside|form|noscript)[^>]*>.*?</\1>", " ", html)
    paragraphs = re.findall(r"(?is)<p[^>]*>(.*?)</p>", html)
    text = " ".join(re.sub(r"<[^>]+>", " ", p) for p in paragraphs)
    if len(text.split()) < MIN_USEFUL_WORDS:
        text = re.sub(r"<[^>]+>", " ", html)
    text = unescape(re.sub(r"\s+", " ", text)).strip()
    return text


def title_from_html(html: str) -> str:
    """Pull the best available title from meta tags."""
    for pattern in (
        r'<meta[^>]+property=["\']og:title["\'][^>]+content=["\']([^"\']+)',
        r'<meta[^>]+name=["\']twitter:title["\'][^>]+content=["\']([^"\']+)',
        r"<title[^>]*>(.*?)</title>",
        r"<h1[^>]*>(.*?)</h1>",
    ):
        match = re.search(pattern, html, re.IGNORECASE | re.DOTALL)
        if match:
            title = unescape(re.sub(r"<[^>]+>", " ", match.group(1)))
            title = re.sub(r"\s+", " ", title).strip()
            if title:
                return title
    return ""


# ----------------------------------------------------------------------
# Main entry point
# ----------------------------------------------------------------------
def extract(url: str, enrich_thin: bool = True) -> Article:
    """Extract a clean Article from any URL, trying every method in turn.

    When the page turns out to be too thin to support a video, the pages it
    links to are checked for supporting material. Set ``enrich_thin`` to False
    to read exactly one page.
    """
    url = normalize_url(url)
    if not is_valid_url(url):
        raise ExtractionError("That does not look like a valid web address.")

    host = urlparse(url).netloc.lower()

    if any(domain in host for domain in YOUTUBE_HOSTS):
        article = extract_youtube(url)
        if article and article.word_count >= 5:
            LOGGER.info("Extracted YouTube metadata: %d words.", article.word_count)
            return article
        LOGGER.info("YouTube metadata was thin; falling back to page extraction.")

    html = fetch_html(url)
    if not html:
        raise ExtractionError(
            "The page could not be downloaded. It may be blocked, offline, or require a login."
        )

    title = ""
    text = ""
    author = ""
    published = ""
    site = ""

    try:
        import trafilatura

        extracted = trafilatura.extract(
            html, include_comments=False, include_tables=False, favor_precision=True
        )
        if extracted:
            text = extracted.strip()
        metadata = trafilatura.extract_metadata(html)
        if metadata:
            title = metadata.title or ""
            author = _clean_author(metadata.author or "")
            published = metadata.date or ""
            site = metadata.sitename or ""
    except ImportError:
        LOGGER.info("trafilatura is not installed; using the built-in HTML fallback.")
    except Exception as exc:  # noqa: BLE001 - never let extraction crash the run
        LOGGER.info("trafilatura failed (%s); using the built-in fallback.", str(exc)[:70])

    if len(text.split()) < MIN_USEFUL_WORDS:
        fallback_text = strip_html(html)
        if len(fallback_text.split()) > len(text.split()):
            text = fallback_text

    title = title or title_from_html(html)
    site = site or host.replace("www.", "")

    if len(text.split()) < MIN_USEFUL_WORDS:
        if title:
            raise ExtractionError(
                f"Only the headline could be read from this page ('{title[:60]}'). "
                "The article body is probably behind a paywall or loaded with JavaScript. "
                "Try a different link, or paste the text as a custom topic."
            )
        raise ExtractionError(
            "No readable article text was found. The page may be a paywall, a login "
            "screen, or built entirely with JavaScript."
        )

    # Trim very long articles: the script only needs the substance, and a huge prompt
    # is slow and can exceed the model context.
    words = text.split()
    if len(words) > 8000:
        # The analyzer condenses by importance, so only absurdly long pages are cut.
        text = " ".join(words[:8000])

    article = Article(
        url=url, title=title or site, text=text, author=author,
        published=published, site=site, source_type="article",
    )

    # A thin page cannot support a full script on its own, so the pages it links
    # to are checked for material that actually names this subject.
    if enrich_thin and article.word_count < THIN_PAGE_WORDS:
        _add_supporting_material(article, html)

    LOGGER.info(
        "Extracted '%s' from %s (%d words%s).",
        article.title[:60], site, article.word_count,
        f", +{len(article.supporting_text.split())} supporting" if article.was_enriched else "",
    )
    return article


def _add_supporting_material(article: "Article", html: str) -> None:
    """Top up a thin article in place, never raising if enrichment fails."""
    try:
        from utility.articles.source_enricher import enrich as enrich_sources

        result = enrich_sources(article, extract_plain, html=html)
        if not result.used:
            return
        blocks = [
            f"[Supporting source: {source.title}]\n{source.text}"
            for source in result.sources
        ]
        article.supporting_text = "\n\n".join(blocks)
        article.supporting_sources = [
            {"title": s.title, "url": s.url, "mentions": s.mentions,
             "words": len(s.text.split())}
            for s in result.sources
        ]
    except Exception as exc:  # noqa: BLE001 - enrichment is a bonus, never required
        LOGGER.info("Enrichment skipped: %s", str(exc)[:80])


def extract_plain(url: str) -> Article:
    """Extract a single page without following its links.

    Used when reading a linked page, so enrichment cannot recurse.
    """
    return extract(url, enrich_thin=False)


# ----------------------------------------------------------------------
# Turning an article into video settings
# ----------------------------------------------------------------------
# Article category -> this project's own script styles. Every name is
# validated at import, so a typo cannot silently narrow the choice.
CATEGORY_STYLE_HINTS = {
    "Technology": ["technology", "explainer", "what_if", "science"],
    "Science": ["science", "space", "nature", "explainer", "myth_busting"],
    "Business": ["finance", "case_study", "comparison", "mistakes"],
    "Health": ["health", "psychology", "explainer", "tutorial"],
    "Politics": ["news", "explainer", "opinion", "history"],
    "Sports": ["motivational", "countdown", "listicle", "biography"],
    "Entertainment": ["listicle", "countdown", "story", "facts"],
    "Culture": ["history", "story", "travel", "biography"],
    "Mystery": ["mystery", "true_crime", "what_if", "history"],
    "Environment": ["nature", "ocean", "animals", "disaster", "survival"],
}

from utility.script.video_styles import VIDEO_STYLES as _ALL_STYLES  # noqa: E402

_unknown_hints = {n for names in CATEGORY_STYLE_HINTS.values() for n in names
                  if n not in _ALL_STYLES}
if _unknown_hints:  # pragma: no cover
    raise RuntimeError(
        f"CATEGORY_STYLE_HINTS names unknown styles: {_unknown_hints}"
    )

CATEGORY_KEYWORDS = {
    "Technology": ["ai", "software", "chip", "app", "startup", "algorithm", "robot", "data",
                    "computer", "quantum", "cyber", "internet", "phone", "model"],
    "Science": ["study", "research", "scientist", "nasa", "space", "physics", "gene", "brain",
                 "discovery", "experiment", "telescope", "cells", "species"],
    "Business": ["market", "economy", "revenue", "company", "stock", "investor", "price",
                  "billion", "million", "profit", "trade", "bank"],
    "Health": ["health", "patient", "disease", "doctor", "vaccine", "mental", "sleep", "diet",
                "therapy", "cancer", "medical"],
    "Politics": ["government", "election", "president", "minister", "policy", "law", "senate",
                  "parliament", "vote", "court"],
    "Sports": ["match", "player", "team", "league", "goal", "championship", "olympic", "coach"],
    "Entertainment": ["film", "movie", "album", "series", "actor", "music", "show", "netflix"],
    "Mystery": ["mystery", "unexplained", "unknown", "secret", "ancient", "disappeared"],
    "Environment": ["climate", "ocean", "forest", "wildlife", "emissions", "species", "pollution",
                     "temperature", "ice", "coral"],
}


def categorize(article: Article) -> str:
    """Guess the subject area, weighting the title far above the body text."""
    title = f" {article.title.lower()} "
    body = f" {article.text[:2000].lower()} "
    scores: Dict[str, float] = {}
    for category, words in CATEGORY_KEYWORDS.items():
        score = 0.0
        for word in words:
            # Whole-word matches only, so "ai" does not match "said" or "again".
            pattern = r"\b" + re.escape(word) + r"\b"
            score += len(re.findall(pattern, title)) * 5.0
            score += len(re.findall(pattern, body)) * 1.0
        scores[category] = score
    best = max(scores.items(), key=lambda item: item[1])
    # A weak signal means the text is general interest rather than a specialist topic.
    return best[0] if best[1] >= 3 else "Culture"


def suggest_settings(
    article: Article, duration_seconds: Optional[int] = None, analysis: Any = None
) -> Dict[str, Any]:
    """Derive the full set of video settings from an extracted and analyzed article."""
    
    from utility.captions.caption_styles import style_for_video_style
    from utility.media.media_sources import music_moods_for_style
    from utility.script.video_styles import VIDEO_STYLES
    from utility.tts.voices import describe, pick_voice

    if analysis is None:
        from utility.script.script_generator import clamp_auto_duration

    if analysis is None:
        from utility.articles.article_analyzer import analyze as _analyze

        analysis = _analyze(article)
    if duration_seconds is None:
        duration_seconds = analysis.recommended_duration

    # Held inside the Shorts window however long the article is. A dense piece
    # can support a five-minute script, but the visuals cannot: the footage is
    # stock, and there are not enough distinct relevant clips in the free
    # catalogues to carry five minutes without the same shots coming round
    # again. A tight short beats a padded long one, and everything this mode
    # produces is destined for a vertical feed anyway.
    duration_seconds = clamp_auto_duration(duration_seconds)

    category = categorize(article)
    candidates = [s for s in CATEGORY_STYLE_HINTS.get(category, [])
                  if s in VIDEO_STYLES]
    style_name = _style_for_emotion(analysis.emotion, candidates)

    # Always vertical, because everything this mode produces is a Short.
    orientation = "portrait"
    voice = pick_voice(style_name, analysis.clean_title)

    return {
        "topic": analysis.clean_title,
        "summary": analysis.summary,
        "emotion": analysis.emotion,
        "substance_score": round(analysis.substance_score, 1),
        "recommended_duration": analysis.recommended_duration,
        "duration_range": analysis.duration_range,
        "key_facts": [f.text for f in analysis.key_facts[:6]],
        "numbers": analysis.numbers[:8],
        "entities": analysis.entities[:8],
        "quotes": analysis.quotes[:3],
        "category": category,
        "video_style": style_name,
        "style_options": candidates or ["explainer"],
        "voice": voice,
        "voice_description": describe(voice),
        "duration_seconds": duration_seconds,
        "orientation": orientation,
        "caption_style": style_for_video_style(style_name),
        "music_mood": music_moods_for_style(style_name),
        "sfx_density": "high" if duration_seconds < 60 else "medium",
        "source_url": article.url,
        "source_site": article.site,
    }


def _style_for_emotion(emotion: str, candidates: List[str]) -> str:
    """Pick the style that matches the article's emotional angle."""
    from utility.script.video_styles import VIDEO_STYLES

    preference = {
        "alarming": ["disaster", "news", "survival", "mistakes"],
        "hopeful": ["motivational", "explainer", "health", "story"],
        "surprising": ["facts", "what_if", "mystery", "myth_busting"],
        "controversial": ["opinion", "news", "myth_busting", "true_crime"],
        "inspiring": ["motivational", "biography", "story", "history"],
    }
    for name in preference.get(emotion, []):
        if name in candidates and name in VIDEO_STYLES:
            return name
    if candidates:
        return candidates[0]
    for name in preference.get(emotion, []):
        if name in VIDEO_STYLES:
            return name
    return "explainer"


def build_script_brief(article: Article) -> str:
    """Build the source material block handed to the script generator."""
    parts = [f"SOURCE ARTICLE: {article.title}"]
    if article.site:
        parts.append(f"PUBLISHER: {article.site}")
    if article.published:
        parts.append(f"PUBLISHED: {article.published}")
    parts.append(f"URL: {article.url}")
    parts.append("")
    parts.append("ARTICLE CONTENT:")
    parts.append(article.text)
    return "\n".join(parts)
